dist: trusty
group: deprecated-2017Q2
sudo: required
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.4
before_install:
  - rvm 2.1.10 do gem install mime-types -v 2.6.2
  - gem install bundler
before_script:
  - "sudo touch /var/log/stripe-mock-server.log"
  - "sudo chown travis /var/log/stripe-mock-server.log"
script: "bundle exec rspec && bundle exec rspec -t live"

env:
  global:
    - IS_TRAVIS=true STRIPE_TEST_SECRET_KEY_A=sk_test_sXdhUWu3NhrB7r1tkK0zZfMW STRIPE_TEST_SECRET_KEY_B=sk_test_uPfIX9ziFNloXwtSdDPJTdnh STRIPE_TEST_SECRET_KEY_C=sk_test_waSy1TaP2RNEpoz9t2pFCysm STRIPE_TEST_SECRET_KEY_D=sk_test_Z1mQZNehRFmI3EN9mHnMafnq

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/44a1f4718ae2efb67eac
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
