dist: trusty
group: deprecated-2017Q2
sudo: required
language: ruby
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3

before_script:
  - "sudo touch /var/log/stripe-mock-server.log"
  - "sudo chown travis /var/log/stripe-mock-server.log"

env:
  global:
    - STRIPE_TEST_SECRET_KEY=sk_test_BsztzqQjzd7lqkgo1LjEG5DF00KzH7tWKF
  matrix:
    - STRIPE_API_VERSION=2020-03-02

script: "bundle exec rspec && bundle exec rspec -t live"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/44a1f4718ae2efb67eac
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

